export default function login(){
    return (
      <div style={styles}>
        <h1>CS FRAGS</h1>
        <p>Generated by create next app</p>
      </div>
    );
}

const styles = {
    height: '100vh',
    width: '100vw',
    padding: '0 20px',
}